
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 09 17:55:19 CEST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class CalculetteSymbol {
  /* terminals */
  public static final int TIMES = 6;
  public static final int AND = 10;
  public static final int EQUAL_SUP = 17;
  public static final int PLUS = 4;
  public static final int SUP = 19;
  public static final int OR = 11;
  public static final int EQUAL = 14;
  public static final int T = 21;
  public static final int EQUAL_NOT = 15;
  public static final int NOT = 9;
  public static final int EQUAL_INF = 16;
  public static final int INF = 18;
  public static final int EQUI = 13;
  public static final int F = 22;
  public static final int SEMIC = 20;
  public static final int NUMBER = 23;
  public static final int EOF = 0;
  public static final int MINUS_U = 8;
  public static final int DIVIDE = 7;
  public static final int MINUS = 5;
  public static final int error = 1;
  public static final int IMPLY = 12;
  public static final int RPAR = 3;
  public static final int LPAR = 2;
}

