
public enum MyEnumType {
	// types simples
	CHARACTER, INTEGER, UINTEGER, BIGINTEGER, UBIGINTEGER, STRING, BOOLEAN, REAL, 
	ARROW, ARRAY, ENUM, INTERVALS, 	
	PLUS, MINUS, DIVIDE, TIMES, 

	ALLOC,

	ERROR
}
