
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 01 21:18:17 CET 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class MySymbol {
  /* terminals */
  public static final int DIVIDE = 7;
  public static final int EQUAL_INF = 15;
  public static final int LBRACKET = 20;
  public static final int CHAR = 32;
  public static final int CASE = 38;
  public static final int SEMIC = 19;
  public static final int INTEGER = 27;
  public static final int MINUS = 5;
  public static final int NOT = 9;
  public static final int AND = 10;
  public static final int RPAR = 3;
  public static final int INF = 17;
  public static final int OR = 11;
  public static final int BOOL = 31;
  public static final int DOTDOT = 22;
  public static final int PLUS = 4;
  public static final int QUOTE = 24;
  public static final int EOF = 0;
  public static final int EQUAL_SUP = 16;
  public static final int OD = 41;
  public static final int RBRACKET = 21;
  public static final int EQUAL = 13;
  public static final int TRUE = 43;
  public static final int error = 1;
  public static final int BIGINTEGER = 28;
  public static final int COMA = 23;
  public static final int NUMBER = 45;
  public static final int EQ = 12;
  public static final int SWITCH = 37;
  public static final int UBIGINTEGER = 30;
  public static final int REAL = 33;
  public static final int TIMES = 6;
  public static final int ARROW = 35;
  public static final int LBRACE = 25;
  public static final int ENUM = 34;
  public static final int END_SWITCH = 42;
  public static final int WHILE = 39;
  public static final int SUP = 18;
  public static final int RBRACE = 26;
  public static final int UINTEGER = 29;
  public static final int STRING = 36;
  public static final int LPAR = 2;
  public static final int MINUS_U = 8;
  public static final int FALSE = 44;
  public static final int STRINGCONTENT = 46;
  public static final int DO = 40;
  public static final int EQUAL_NOT = 14;
}

